ORG 0000H                ;STARTING THE PROGRAM FROM ORIGIN ADDRESS(0000H)
      SETB P0.0          ;CLEAR SWITCH1
      SETB P0.1          ;CLEAR SWITCH2
      SETB P1.0          ;CLEAR LED
LOOP: CLR C              ;CARRY BIT IS SET
      ORL C,/P0.1        ;OR OPERTION WITH CARRY AND COMPLEMENT OF PORT 0.1
      ANL C,/P0.0        ;AND OPERATION WITH CARRY BIT AND CMPLEMENT OF PORT 0.0
      CPL C              ;COMPLEMENT CARRY-BIT
      MOV P1.0,C         ;MOVING THE CONTENT OF CARRY BIT TO PORT 1.0
      SJMP LOOP          ;JUMPING TO LOOP LABEL TO LOOP THE PROCESS
END
