ORG 0000H                ;STARTING THE PROGRAM FROM ORIGIN ADDRESS(0000H)
      SETB P0.0          ;CLEAR SWITCH1
      SETB P0.1          ;CLEAR SWITCH2
      SETB P1.0          ;CLEAR LED
LOOP: CLR C              ;CARRY BIT IS SET
      MOV C,P0.0         ;MOVING THE CONTENT OF PORT 0.0 TO CARRY BIT
      ANL C,P0.1         ;AND OPERATION WITH CARRY BIT AND COMPLEMENT OF PORT 0.1
      MOV P1.0,C         ;MOVING THE CONTENT OF CARRY BIT TO PORT 1.0
      SJMP LOOP          ;JUMPING TO LOOP LABEL TO LOOP THE PROCESS
END
      

